name: Deploy Only

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build & Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_API_URL }}

      - name: Build images and save outputs
        id: build_all
        run: |
          TAG=${GITHUB_SHA::8}

          # API
          docker build -t ${{ secrets.ECR_API_URL }}:$TAG ./api-gateway
          docker push ${{ secrets.ECR_API_URL }}:$TAG

          # PRODUCT
          docker build -t ${{ secrets.ECR_PRODUCT_URL }}:$TAG ./product-service
          docker push ${{ secrets.ECR_PRODUCT_URL }}:$TAG

          # INVENTORY
          docker build -t ${{ secrets.ECR_INVENTORY_URL }}:$TAG ./inventory-service
          docker push ${{ secrets.ECR_INVENTORY_URL }}:$TAG

          # Guardamos las imÃ¡genes en un archivo y lo subimos como artifact
          echo "API_IMAGE=${{ secrets.ECR_API_URL }}:$TAG" >> image-outputs.env
          echo "PRODUCT_IMAGE=${{ secrets.ECR_PRODUCT_URL }}:$TAG" >> image-outputs.env
          echo "INVENTORY_IMAGE=${{ secrets.ECR_INVENTORY_URL }}:$TAG" >> image-outputs.env

      - name: Upload image outputs
        uses: actions/upload-artifact@v4
        with:
          name: image-outputs
          path: image-outputs.env

  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download image outputs
        uses: actions/download-artifact@v4
        with:
          name: image-outputs

      - name: Load variables
        run: |
          source image-outputs.env
          echo "API_IMAGE=$API_IMAGE"
          echo "PRODUCT_IMAGE=$PRODUCT_IMAGE"
          echo "INVENTORY_IMAGE=$INVENTORY_IMAGE"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Prepare Task Definition
        run: |
          cp infra/ecs-task/taskdef.json taskdef.json

          sed -i "s|__API_IMAGE__|$API_IMAGE|" taskdef.json
          sed -i "s|__PRODUCT_IMAGE__|$PRODUCT_IMAGE|" taskdef.json
          sed -i "s|__INVENTORY_IMAGE__|$INVENTORY_IMAGE|" taskdef.json

      - name: Register Task Definition
        id: reg
        run: |
          OUT=$(aws ecs register-task-definition --cli-input-json file://taskdef.json)
          ARN=$(echo $OUT | jq -r '.taskDefinition.taskDefinitionArn')
          echo "TASK_ARN=$ARN" >> $GITHUB_OUTPUT

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster "${{ secrets.ECS_CLUSTER_NAME }}" \
            --service "${{ secrets.ECS_SERVICE_NAME }}" \
            --task-definition "${{ steps.reg.outputs.TASK_ARN }}" \
            --force-new-deployment \
            --desired-count 1

      - name: Completed
        run: echo "ðŸš€ Deploy ejecutado correctamente."

